
acme_demo_homepage:
    path:     /
    defaults: { _controller: AcmeDemoBundle:Default:index }
    
acme_demo_connact_us:
    path:     /connact
    defaults: { _controller: AcmeDemoBundle:Default:connact}
    

 
_notice:
    path:    /notice
    defaults: { _controller: AcmeDemoBundle:Default:notice }
    
_new_conference:
    path:    /admin/new
    defaults: { _controller: AcmeDemoBundle:Conference:new}

_modify_conference:
    path:    /admin/modify/{id}
    defaults: { _controller: AcmeDemoBundle:Conference:modify}
    
_modify_done_conference:
    path:    /admin/modifydone/{id}
    defaults: { _controller: AcmeDemoBundle:Conference:modifydone}    
    
_delete_conference:
    path:     /admin/delete/{id}
    defaults: { _controller: AcmeDemoBundle:Conference:delete}
    
_sign_show:
    path:     /signshow
    defaults: { _controller: AcmeDemoBundle:SignUp:signShow}
  

_sign_up:
    path:     /signup/{id}
    defaults: { _controller: AcmeDemoBundle:SignUp:sign}
    
_dissign:
    path:     /dissign/{id}
    defaults: { _controller: AcmeDemoBundle:SignUp:dissign}

_down:
    path:     /admin/down/{id}
    defaults: { _controller: AcmeDemoBundle:Conference:signUpDownload}
    
    
_schedule:
    path:     /schedule
    defaults: { _controller: AcmeDemoBundle:Default:schedule }

_set_home:
    path:    /admin/sethome/{id}
    defaults: { _controller: AcmeDemoBundle:Conference:setHome}

_mail:
    path:     /admin/mail
    defaults: { _controller: AcmeDemoBundle:Default:mail }
    
_send_mail:
    path:    /admin/sendmail
    defaults: { _controller: AcmeDemoBundle:Default:sendmail }
    
    
_load_mail:
    path:    /admin/loadmail
    defaults: { _controller: AcmeDemoBundle:Default:loadmail}
    

_mail_participated:
    path:    /participated/{email}
    defaults: { _controller: AcmeDemoBundle:Default:participated}  
    
    
_download_participated:
    path:    /admin/downparticipated
    defaults: { _controller: AcmeDemoBundle:Default:downParticipated}  