# src/AppBundle/Resources/config/validation.yml
Acme\DemoBundle\Entity\SignUp:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [user,conference]
            errorPath: user
            message: 'This user is already sign up in that conference.'    
